apiVersion: klot.io/v1
kind: KlotIOApp
metadata:
  name: chore-button.nandy.io
spec:
  namespace: chore-button-nandy-io
  description: Chore Button - Nandy I/O
  manifests:
  - path: daemon/kubernetes/daemon.yaml
  requires:
  - name: people.nandy.io
    source:
      site: github.com
      repo: nandy-io/people
    integrations:
    - path: daemon/forms/person.fields.yaml
  - name: chore.nandy.io
    source:
      site: github.com
      repo: nandy-io/chore
    integrations:
    - path: daemon/forms/routine.fields.yaml
  - name: button.nandy.io
    source:
      site: github.com
      repo: nandy-io/button
