apiVersion: klot.io/v1
kind: App
metadata:
  name: chore-button.nandy.io
  version: v0.1
  description: Chore Button - Nandy I/O
spec:
  namespace: chore-button-nandy-io
  manifests:
  - path: kubernetes/namespace.yaml
  - path: daemon/kubernetes/daemon.yaml
  requires:
  - name: chore.nandy.io
    source:
      site: github.com
      repo: nandy-io/chore
  - name: button.nandy.io
    source:
      site: github.com
      repo: nandy-io/button
